version: "3"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    privileged: true
    healthcheck:
      interval: 5s
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1",
        ]
      timeout: 10s
      retries: 3
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - network
    volumes:
      - mariadb_data:/var/lib/mysql
    restart:  on-failure
    init: true

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - network
    volumes:
      - wordpress_data:/var/www/html
    restart:  on-failure
    init: true

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - network
    volumes:
      - wordpress_data:/var/www/html
    restart:  on-failure
    init: true

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mysql

networks:
  network:
    driver: bridge
