version: "3"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - network
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - network
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - network
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mysql

networks:
  network:
    driver: bridge
